//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNSChanger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DNSChanger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter name not selected..
        /// </summary>
        internal static string AdapterNameNotSelected {
            get {
                return ResourceManager.GetString("AdapterNameNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNSChanger.Adapter.
        /// </summary>
        internal static string DNSChanger_Adapter {
            get {
                return ResourceManager.GetString("DNSChanger_Adapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the DNS.XML file exists duplicate DNS name!.
        /// </summary>
        internal static string DuplicateInDNSFile {
            get {
                return ResourceManager.GetString("DuplicateInDNSFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n.
        /// </summary>
        internal static string EnterChar {
            get {
                return ResourceManager.GetString("EnterChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred!.
        /// </summary>
        internal static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Esc}.
        /// </summary>
        internal static string ESC {
            get {
                return ResourceManager.GetString("ESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DNS name already exists, please change it and try again..
        /// </summary>
        internal static string ExistsDuplicateDNS {
            get {
                return ResourceManager.GetString("ExistsDuplicateDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get new update.
        /// </summary>
        internal static string GetNewUpdate {
            get {
                return ResourceManager.GetString("GetNewUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version\t{Resources.Version}\nUpdate version\t{UpdateVersion}\nShould the update be performed?.
        /// </summary>
        internal static string IsUpdate {
            get {
                return ResourceManager.GetString("IsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Loading {
            get {
                object obj = ResourceManager.GetObject("Loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DNS required for the update could not be found!.
        /// </summary>
        internal static string NodeNotFind {
            get {
                return ResourceManager.GetString("NodeNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Resources.Version}.
        /// </summary>
        internal static string ResourcesVersion {
            get {
                return ResourceManager.GetString("ResourcesVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://hmovaghari.github.io/#contact:en.
        /// </summary>
        internal static string SupportUrl {
            get {
                return ResourceManager.GetString("SupportUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \t.
        /// </summary>
        internal static string TabChar {
            get {
                return ResourceManager.GetString("TabChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate.
        /// </summary>
        internal static string TagAlternate {
            get {
                return ResourceManager.GetString("TagAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS.
        /// </summary>
        internal static string TagDNS {
            get {
                return ResourceManager.GetString("TagDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string TagItem {
            get {
                return ResourceManager.GetString("TagItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TagName {
            get {
                return ResourceManager.GetString("TagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred.
        /// </summary>
        internal static string TagPreferred {
            get {
                return ResourceManager.GetString("TagPreferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string TextProperties {
            get {
                return ResourceManager.GetString("TextProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This adapter not connected.
        /// </summary>
        internal static string ThisAdapterNotConnected {
            get {
                return ResourceManager.GetString("ThisAdapterNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://hmovaghari.github.io/root/DNSChanger/FramworkApp.Update.txt.
        /// </summary>
        internal static string UpdateUrl {
            get {
                return ResourceManager.GetString("UpdateUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {UpdateVersion}.
        /// </summary>
        internal static string UpdateVersion {
            get {
                return ResourceManager.GetString("UpdateVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.3.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS.XML.
        /// </summary>
        internal static string XMLFileName {
            get {
                return ResourceManager.GetString("XMLFileName", resourceCulture);
            }
        }
    }
}
